### ISSUE TITLE
Errors with some websites

### ISSUE THREAD

**Issue by ghost** [F1uYu4n/hashcrack#5]
https://puu.sh/CWTt8/88dd8cd1be.png

[-] xmd5: RequestError
[-] bugbank: Error: 'charmap' codec can't encode characters in position 13-18: character maps to <undefined>
Exception in thread Thread-133:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "hashcrack.py", line 45, in cmd5
    print u"[*] cmd5: {0}".format(re.sub(ur"\u3002.*", u"", result))
  File "C:\python27\lib\encodings\cp866.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-12: character maps to <undefined>

[-] chamd5: NotFound
Exception in thread Thread-138:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "hashcrack.py", line 141, in navisec
    print u"[-] navisec: {0}{1}".format(result, num)
  File "C:\python27\lib\encodings\cp866.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-55: character maps to <undefined>

**Comment by mastercho** [comment]
Having the same issue, I guess because the website is Chinese characters encoding
